# Generated by Django 3.2.9 on 2021-11-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_auto_20211122_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='descr',
            field=models.TextField(),
        ),
    ]
